### ISSUE TITLE
`readMany` for items uses the wrong endpoint

### ISSUE THREAD

**Issue by johnkmzhou** [directus/sdk#142]
### Describe the Bug

When using `directus.items('articles').readMany([2, 3]);` it will use the endpoint `/fields/articles` when it should be using `/items/articles`.

### Directus Version
9.25.1

### SDK Version
10.3.3

**Comment by azrikahar** [comment]
I believe it does use `/fields/articles` to fetch the primary key field _first_, but afterwards it does use `/items/articles` afterwards and uses a filter query using said primary key field, as seen in the original PR: https://github.com/directus/directus/pull/11204

out of curiosity, can you confirm whether `readMany` works when you use an admin credential? (so that you have the necessary permission to fetch the initial `/fields/articles`)

**Comment by johnkmzhou** [comment]
Taking another look at, it does work when the directus_fields endpoint is given public read permission. My initial assumption was that `readMany` works similar to `readOne`. I've already worked around this using
```
directus.items('article').readByQuery({
  filter: { _or: [{ id: 2 }, { id: 3 }] }
});
```

Anyway, thanks for giving me a better understanding of what's going on.
